version: '3.8'

services:
  validator-devel:
    image: validator-devel:debug
    ports:
      - 8080:8080
    volumes:
      - ./modulistica:/modulistica
      - ./validator:/validator
      # - ./settings.yaml:/code/validator_devel/config/settings_template.yaml